services:
  db:
    image: mysql:8
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    hostname: db

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - 8888:8888
